#!/usr/bin/env bun
// Multi-event hook forwarder — captures Claude Code CLI hook events
// (PreToolUse, PostToolUse, UserPromptSubmit, Stop, SubagentStop, SessionStart)
// and forwards them to the ia-flow server so they are re-emitted as log
// entries in `daemon.log`. The server broadcasts them via WebSocket so the
// web UI drawer renders them live without any UI changes (unknown events fall
// into the "other" kind which renders a generic row).
//
// Invocation: `bun hook-tool-use.ts [HookEventName]`
//   - No arg / "PostToolUse": legacy path, emits tool.call + tool.result pair.
//   - "PreToolUse"      → event: 'tool.pre'
//   - "UserPromptSubmit"→ event: 'agent.prompt'
//   - "Stop"            → event: 'agent.stop'
//   - "SubagentStop"    → event: 'subagent.stop'
//   - "SessionStart"    → event: 'agent.session_start'
//
// This file is referenced from the per-run settings.json generated by
// writeRunSettings in base.ts via `new URL('./hook-tool-use.ts', import.meta.url)`.
//
// Design invariants:
// - Silent no-op if IA_FLOW_RUN_ID is not set (covers manual/test runs).
// - `await fetch` with AbortSignal.timeout(3s): process.exit(0) would kill
//   the process before the TCP request is dispatched without the await.
// - Truncates large strings (tool_response, prompt) to 10 KB to bound
//   daemon.log entry sizes.
// - Never throws; all errors are swallowed (`.catch(() => {})`).

export {}

const MAX_BYTES = 10_000
const REQUEST_TIMEOUT_MS = 3_000

const runId = process.env.IA_FLOW_RUN_ID
if (!runId) process.exit(0)

const serverUrl = process.env.IA_FLOW_SERVER_URL ?? 'http://localhost:3001'

const hookName = process.argv[2] ?? 'PostToolUse'

let raw: string
try {
  raw = await Bun.stdin.text()
} catch {
  process.exit(0)
}

let payload: unknown
try {
  payload = JSON.parse(raw)
} catch {
  process.exit(0)
}

const obj = (payload ?? {}) as Record<string, unknown>

function truncate(s: string): string {
  return s.length > MAX_BYTES ? `${s.slice(0, MAX_BYTES)}…[truncated]` : s
}

function stringify(v: unknown): string | undefined {
  if (v === undefined) return undefined
  const s = typeof v === 'string' ? v : JSON.stringify(v)
  return typeof s === 'string' ? truncate(s) : undefined
}

const sessionId = typeof obj.session_id === 'string' ? obj.session_id : 'no-session'

let body: Record<string, unknown>

if (hookName === 'PreToolUse') {
  const toolName = typeof obj.tool_name === 'string' ? obj.tool_name : 'unknown'
  const toolInputRaw = obj.tool_input
  const input =
    toolInputRaw && typeof toolInputRaw === 'object' && !Array.isArray(toolInputRaw)
      ? (toolInputRaw as Record<string, unknown>)
      : {}
  const toolUseId = `${sessionId.slice(0, 8)}-${toolName}-${Date.now()}`
  body = { event: 'tool.pre', runId, toolName, toolUseId, input }
} else if (hookName === 'UserPromptSubmit') {
  const promptRaw = typeof obj.prompt === 'string' ? obj.prompt : ''
  body = { event: 'agent.prompt', runId, prompt: truncate(promptRaw) }
} else if (hookName === 'Stop') {
  const stopReason = stringify(obj.stop_reason ?? obj.reason)
  body = { event: 'agent.stop', runId, ...(stopReason !== undefined ? { stopReason } : {}) }
} else if (hookName === 'SubagentStop') {
  const stopReason = stringify(obj.stop_reason ?? obj.reason)
  body = { event: 'subagent.stop', runId, ...(stopReason !== undefined ? { stopReason } : {}) }
} else if (hookName === 'SessionStart') {
  const source = typeof obj.source === 'string' ? obj.source : undefined
  body = {
    event: 'agent.session_start',
    runId,
    sessionId,
    ...(source !== undefined ? { source } : {}),
  }
} else {
  // PostToolUse (default / legacy — no event field so hook-events router uses
  // the legacy path that emits both tool.call and tool.result).
  const toolName = typeof obj.tool_name === 'string' ? obj.tool_name : 'unknown'
  const toolInputRaw = obj.tool_input
  const input =
    toolInputRaw && typeof toolInputRaw === 'object' && !Array.isArray(toolInputRaw)
      ? (toolInputRaw as Record<string, unknown>)
      : {}
  const toolUseId = `${sessionId.slice(0, 8)}-${toolName}-${Date.now()}`
  const result = stringify(obj.tool_response)
  body = { runId, toolName, toolUseId, input, ...(result !== undefined ? { result } : {}) }
}

// Await is mandatory: without it, process.exit(0) races the TCP dispatch.
// AbortSignal.timeout caps how long Claude Code waits for this hook.
await fetch(`${serverUrl}/api/hook-events`, {
  method: 'POST',
  headers: { 'content-type': 'application/json' },
  body: JSON.stringify(body),
  signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
}).catch(() => {})

process.exit(0)
