import type {
  AgentProviderConfig,
  AnthropicApiSettings,
  ProviderConfig,
  RepoWorkflow,
  SessionKind,
  StepType,
} from '@ia-flow/shared'

/**
 * Opaque handle to the OS-level backing of an async run (a tmux session, an
 * iTerm2 tab, …). Providers that spawn out-of-process work return one so the
 * orchestrator can persist its coordinates, close it on cancel, and watchdog
 * its liveness without knowing which technology backs it.
 *
 *  - `kind` + `id` are what we save to `execution_logs` so a stopped run can
 *    later be identified from the DB.
 *  - `isAlive()` should be cheap and side-effect-free (used by the poller).
 *  - `close()` must be idempotent — the watchdog and the manual cancel path
 *    may both fire, and complete_task / fail_task tools also invoke it.
 */
export interface SessionHandle {
  kind: SessionKind
  id: string
  isAlive: () => Promise<boolean>
  close: () => Promise<void>
}

/** Narrow structural shape of the engine's compiled permission policy — only
 *  the field a provider actually reads (`toolNames`, to compute the
 *  effective tool allow-list). The real `CompiledPolicy` (apps/server's
 *  `application/policy.ts`) satisfies this; providers never see its other
 *  fields (bash whitelist, git scope), which are consumed downstream by
 *  `ToolContext.policy` inside the injected `ToolExecutionPort`. */
export interface PolicyLike {
  toolNames: ReadonlySet<string>
}

/**
 * Input passed to a provider's run() method. Populated by AgentOrchestrator
 * before each agent invocation.
 *
 * The agent learns about repos via the `{{project.repos}}` / `{{task.repos}}`
 * template variables in its prompt. `repoPaths` is the raw name→path map
 * consumed by fs tools (`read_file`, `list_dir`, `grep_files`) to resolve
 * `<repo-name>/relative/path`.
 */
export interface ProviderInput {
  step: StepType
  /** Agent registry id (e.g. "code-reviewer"). Propagated to logs so every
   *  event can be filtered/joined by the agent that produced it. */
  agentId?: string
  /** Project id owning the task. Propagated to logs so the Logs tab in a
   *  project view can filter by projectId. */
  projectId?: string
  /** Correlation id shared by the execution_logs row and every log line
   *  emitted during this run. Generated by AgentOrchestrator. When absent,
   *  providers fall back to generating their own local runId. */
  runId?: string
  taskId: string
  taskTitle: string
  taskDescription: string
  taskType: string
  /** Repos linked to this task by name. */
  repos: string[]
  /** name → absolute filesystem path, wired into ToolContext.repoPaths. */
  repoPaths: Record<string, string>
  prompt: string
  systemPromptBlocks?: Array<{ type: 'text'; text: string }>
  tools?: string[]
  providerConfig?: AgentProviderConfig
  /** Source-specific tool context, opaque to the domain. */
  sourceToolContext?: unknown
  cwd?: string
  workflow?: RepoWorkflow
  /**
   * Nombre canónico de la branch git para esta task (viene de `task.branch` —
   * linked branch de GitHub o valor auto-generado por el engine). Undefined
   * ⇒ providers usan el fallback `task/<taskId>`.
   */
  branch?: string
  /**
   * Absolute filesystem paths that write/edit/exec tools are allowed to touch
   * during this run. Wired into `ToolContext.writePaths` by the anthropic-api
   * provider. Populated by the WorkspaceManager for `implement`-step runs;
   * `undefined` or empty means the run has no writable zones (write tools
   * must refuse).
   */
  writePaths?: string[]
  /**
   * Compiled policy for this dispatch — always present once the agent has
   * any `tools[]`. Threaded from `Agent.compilePolicyPort(agent.tools)` into
   * `ToolContext.policy`, where `bash_run` reads its allow/deny command
   * patterns.
   */
  policy?: PolicyLike
  /** Aborts the run when triggered (e.g. the manual gate detects the source
   *  status has drifted from where the agent was dispatched). Providers
   *  should propagate to any long-running work (fetch calls, spawned
   *  sessions) and clean up so no partial transitions leak. */
  signal?: AbortSignal
}

/**
 * Result of a provider run.
 *   - Sync providers (anthropic-api) return `{ content, mode: 'api' }`.
 *   - Async providers (tmux-claude, iterm-claude) spawn a background
 *     session and return `{ content, mode: 'tmux', tmuxSession? }`. The
 *     final task transition is triggered later by the async agent via
 *     the complete_task / fail_task tools.
 */
export interface ProviderOutput {
  content: string
  mode: 'api' | 'tmux'
  /** Backing OS session for async providers. Absent for `mode: 'api'`.
   *  Orchestrator persists `{kind,id}` to execution_logs, wires `close()`
   *  as the pending entry's `killSession`, and starts a liveness watchdog
   *  against `isAlive()` so a tab the user closes manually can't leave the
   *  execution stuck as "in-flight" forever. */
  session?: SessionHandle
  /** Free-form hint for humans in log lines / UI (e.g. `tmux attach -t xyz`
   *  or `iTerm2 tab`). Not consumed by the orchestrator. */
  attachCmd?: string
  /** Sync providers set this when the run was cut short (e.g. server-side
   *  task budget exhausted, or the internal safety cap tripped). The
   *  orchestrator treats truncated runs as recoverable — it posts a
   *  progress notice instead of running the onFinish transition. */
  truncated?: boolean
  /** Underlying model stop_reason (`end_turn`, `pause_turn`, `max_tokens`,
   *  `hard_iter_cap`, …). Used for observability. */
  stopReason?: string
}

/**
 * How a provider expects to receive its tool catalog.
 *   - `sync`: tools are handed to an LLM API natively (Anthropic `tools:`
 *     array). The engine exposes them via `toolExecution.getToolDefinitions`.
 *   - `async`: no native tool interface — the model runs in a terminal
 *     Claude session and calls back over HTTP. The engine appends a
 *     `toolExecution.buildToolInstructions` markdown block to the prompt
 *     describing each available tool + its curl invocation.
 */
export type ProviderKind = 'sync' | 'async'

export interface IAgentProvider {
  readonly id: string
  readonly kind: ProviderKind
  readonly name: string
  readonly description: string
  run(input: ProviderInput): Promise<ProviderOutput>
}

// ─── Injected ports ─────────────────────────────────────────────────────
//
// Providers in this package never import apps/server's tool registry, DB
// repos, or WorkspaceManager directly — they receive the narrow slice of
// that behavior they actually call, as plain functions, from whoever
// composes them (apps/server's composition/container.ts today).

/** Sandbox context a tool executes in. Mirrors apps/server's
 *  `tools/index.ts::ToolContext` field-for-field, except `policy`, which
 *  this package treats as opaque (it's forwarded, never read, here) — the
 *  concrete `ToolContext` (with a real `CompiledPolicy`) is structurally
 *  assignable wherever this type is expected. */
export interface ToolContext {
  repoPaths: Record<string, string>
  sourceContext?: unknown
  fileSimplifierEnabled?: boolean
  writePaths?: string[]
  taskId?: string
  policy?: unknown
}

export interface LoopOptions {
  onToolCall?: (name: string, input: unknown, toolUseId: string) => void
  onToolResult?: (name: string, result: string, toolUseId: string) => void
  signal?: AbortSignal
  logContext?: Record<string, unknown>
  /** See `LoopOptions.maxPauseTurnRetries` in packages/tools/src/contract.ts
   *  (the implementation's copy of this type) for the full rationale. */
  maxPauseTurnRetries?: number
}

export interface LoopResult {
  text: string
  iters: number
  stopReason: string
  truncated: boolean
}

export interface ToolDefinitionsOptions {
  providerKind?: ProviderKind
  toolNames?: string[]
}

/** The agentic tool-execution engine, injected so `anthropic-api` never
 *  imports apps/server's tool registry directly. */
export interface ToolExecutionPort {
  getToolDefinitions(
    opts?: ToolDefinitionsOptions,
  ): Array<{ name: string; description: string; input_schema: object }>
  executeLoop(
    fetchApi: (messages: any[]) => Promise<any>,
    initialMessages: any[],
    ctx: ToolContext,
    opts?: LoopOptions,
  ): Promise<LoopResult>
}

/** Resolves the per-project/global provider settings blob. Backed by
 *  apps/server's DB-persisted config; injected so providers stay
 *  storage-agnostic. */
export type LoadProviderConfig = () => Promise<ProviderConfig>

/** Resolves the on-disk worktree path for a task, so terminal providers can
 *  point the `claude` CLI's WorktreeCreate hook at the same path the
 *  anthropic-api provider's WorkspaceManager uses. */
export interface WorktreePathResolver {
  worktreePathFor(repoBasePath: string, taskId: string): string
}

// ─── Pure config helpers (no I/O — safe to own here) ───────────────────

export const DEFAULT_ANTHROPIC_SETTINGS: AnthropicApiSettings = {
  model: 'claude-sonnet-4-6',
  anthropicVersion: '2023-06-01',
  anthropicBeta: [
    'claude-code-20250219',
    'oauth-2025-04-20',
    'interleaved-thinking-2025-05-14',
    'context-management-2025-06-27',
    'prompt-caching-scope-2026-01-05',
    'extended-cache-ttl-2025-04-11',
  ],
  systemPrompt: [],
  thinking: { type: 'adaptive' },
  stream: true,
  responseLanguage: 'español',
}

export const DEFAULT_TERMINAL_SETTINGS = {}

export const DEFAULT_PROVIDER_CONFIG: ProviderConfig = {
  steps: {
    'refine-functional': 'anthropic-api',
    'refine-technical': 'anthropic-api',
    implement: 'tmux-claude',
  },
  anthropicApi: DEFAULT_ANTHROPIC_SETTINGS,
  tmuxClaude: DEFAULT_TERMINAL_SETTINGS,
  itermClaude: DEFAULT_TERMINAL_SETTINGS,
}

/** Resolves the provider id and merged settings for a given step. Pure —
 *  step-level overrides take precedence over provider-level defaults. */
export function resolveStepSettings(
  step: StepType,
  config: ProviderConfig,
): { providerId: string; settings: AnthropicApiSettings } {
  const stepCfg = config.steps[step]
  if (typeof stepCfg === 'string') {
    return { providerId: stepCfg, settings: config.anthropicApi }
  }
  if (!stepCfg || typeof stepCfg === 'string') {
    throw new Error(`No provider configured for step '${step}'`)
  }
  const { provider, ...overrides } = stepCfg
  return { providerId: provider, settings: { ...config.anthropicApi, ...overrides } }
}
