import type {
  AgentProviderConfig,
  AnthropicApiSettings,
  ProviderConfig,
  RepoWorkflow,
  SessionKind,
  StepType,
  WorkspacePlan,
  WorkspaceRequest,
} from '@ia-flow/shared'
import type { Admission, AdmissionRequest } from './admission.js'

/**
 * Opaque handle to the OS-level backing of an async run (a tmux session, an
 * iTerm2 tab, …). Providers that spawn out-of-process work return one so the
 * orchestrator can persist its coordinates, close it on cancel, and watchdog
 * its liveness without knowing which technology backs it.
 *
 *  - `kind` + `id` are what we save to `execution_logs` so a stopped run can
 *    later be identified from the DB.
 *  - `liveness()` should be cheap and side-effect-free (used by the poller).
 *  - `close()` must be idempotent — the watchdog and the manual cancel path
 *    may both fire, and complete_task / fail_task tools also invoke it.
 */
export interface SessionHandle {
  kind: SessionKind
  id: string
  liveness: () => Promise<Liveness>
  close: () => Promise<void>
}

/**
 * Estado de una sesión async, con TRES valores a propósito.
 *
 * `unknown` no es un lujo de tipos: es la respuesta honesta cuando la sonda
 * no pudo preguntar (tmux no ejecutable, AppleScript colgado, el gateway que
 * hospeda la sesión reinició y ya no la tiene en memoria). Con un `boolean`
 * cada adapter tenía que colapsar ese tercer caso a `true` o `false` por su
 * cuenta, y ahí se coló el incidente que motivó esto: el gateway contestaba
 * "no la conozco" y `RemoteAgentProvider` lo leía como "está muerta", así que
 * el watchdog abandonaba runs que seguían trabajando.
 *
 * La regla que ordena a todos los adapters: **la muerte necesita evidencia
 * positiva**. Sólo devolvé `dead` cuando algo que SÍ sabe (el servidor de
 * tmux, iTerm, el gateway que tiene la sesión) contestó que no existe. Si la
 * sonda falló, devolvé `unknown` — la política de qué hacer con eso es del
 * watchdog (`packages/agent-engine/src/session-watchdog.ts`), no del adapter.
 */
export type Liveness = 'alive' | 'dead' | 'unknown'

/** Narrow structural shape of the engine's compiled permission policy — only
 *  the field a provider actually reads (`toolNames`, to compute the
 *  effective tool allow-list). The real `CompiledPolicy` (apps/server's
 *  `application/policy.ts`) satisfies this; providers never see its other
 *  fields (bash whitelist, git scope), which are consumed downstream by
 *  `ToolContext.policy` inside the injected `ToolExecutionPort`. */
export interface PolicyLike {
  toolNames: ReadonlySet<string>
}

/**
 * Input passed to a provider's run() method. Populated by AgentOrchestrator
 * before each agent invocation.
 *
 * The agent learns about repos via the `{{project.repos}}` / `{{task.repos}}`
 * template variables in its prompt. `repoPaths` is the raw name→path map
 * consumed by fs tools (`read_file`, `list_dir`, `grep_files`) to resolve
 * `<repo-name>/relative/path`.
 */
export interface ProviderInput {
  step: StepType
  /** Agent registry id (e.g. "code-reviewer"). Propagated to logs so every
   *  event can be filtered/joined by the agent that produced it. */
  agentId?: string
  /** Project id owning the task. Propagated to logs so the Logs tab in a
   *  project view can filter by projectId. */
  projectId?: string
  /** Correlation id shared by the execution_logs row and every log line
   *  emitted during this run. Generated by AgentOrchestrator. When absent,
   *  providers fall back to generating their own local runId. */
  runId?: string
  taskId: string
  taskTitle: string
  taskDescription: string
  taskType: string
  /** Número de issue del source (GitHub). Alimenta el nombre legible del
   *  worktree; ausente en sources que no numeran issues. */
  issueNumber?: number
  /** Repos linked to this task by name. */
  repos: string[]
  /** Logins asignados al issue. Un provider remoto los usa en su admisión
   *  ("sólo tomo los issues de mi dueño") — misma razón por la que viajan
   *  repos/taskType: hechos de la tarea que el gateway evalúa en su borde. */
  assignees?: string[]
  /** name → absolute filesystem path, wired into ToolContext.repoPaths. */
  repoPaths: Record<string, string>
  prompt: string
  systemPromptBlocks?: Array<{ type: 'text'; text: string }>
  tools?: string[]
  /** Salidas elegibles del agente (ver `AgentOutcomesSchema.exits`). Viaja
   *  hasta `getToolDefinitions` para armar el enum de `select_exit`: el modelo
   *  sólo puede nombrar aristas declaradas. Vacío/ausente ⇒ la tool no se
   *  ofrece. */
  selectableExits?: Array<{ name: string; when?: string }>
  providerConfig?: AgentProviderConfig
  /** Source-specific tool context, opaque to the domain. */
  sourceToolContext?: unknown
  cwd?: string
  /**
   * Cómo alcanzar al daemon que originó el dispatch.
   *
   * Sólo lo llenan los providers remotos: un provider local ya corre en la
   * misma máquina que el daemon y su default de `localhost` es correcto. Del
   * otro lado de un gateway no lo es —`localhost` ahí es el gateway, no el
   * daemon— y esa URL no es decorativa: por ella viajan las tools del agente
   * (`/api/mcp`) y el callback con el que cierra su trabajo. Sin esto, un run
   * async remoto arrancaba sin ninguna tool y sin poder reportar el final.
   */
  daemonUrl?: string
  workflow?: RepoWorkflow
  /**
   * Nombre canónico de la branch git para esta task (viene de `task.branch` —
   * linked branch de GitHub o valor auto-generado por el engine). Undefined
   * ⇒ providers usan el fallback `task/<taskId>`.
   */
  branch?: string
  /**
   * Absolute filesystem paths that write/edit/exec tools are allowed to touch
   * during this run. Wired into `ToolContext.writePaths` by the anthropic-api
   * provider. Lo llena `prepareWorkspace` (intersectado contra el permiso que
   * declara el engine); `undefined` o vacío = el run no tiene zonas
   * escribibles y los write tools rechazan.
   */
  writePaths?: string[]
  /**
   * La INTENCIÓN del workspace, no su resultado: qué repos, qué branch, si el
   * agente escribe. Viaja con el input para que quien realmente va a correr
   * el agente pueda resolver el terreno en SU disco — es lo que le permite al
   * gateway remoto clonar y armar su propio worktree en vez de recibir paths
   * de la máquina que originó el dispatch.
   */
  workspace?: WorkspaceRequest
  /**
   * Compiled policy for this dispatch — always present once the agent has
   * any `tools[]`. Threaded from `Agent.compilePolicyPort(agent.tools)` into
   * `ToolContext.policy`, where `bash_run` reads its allow/deny command
   * patterns.
   */
  policy?: PolicyLike
  /** Aborts the run when triggered (e.g. the manual gate detects the source
   *  status has drifted from where the agent was dispatched). Providers
   *  should propagate to any long-running work (fetch calls, spawned
   *  sessions) and clean up so no partial transitions leak. */
  signal?: AbortSignal
}

/**
 * Result of a provider run.
 *   - Sync providers (anthropic-api) return `{ content, mode: 'api' }`.
 *   - Async providers (tmux-claude, iterm-claude) spawn a background
 *     session and return `{ content, mode: 'tmux', tmuxSession? }`. The
 *     final task transition is triggered later by the async agent via
 *     the complete_task / fail_task tools.
 */
export interface ProviderOutput {
  content: string
  mode: 'api' | 'tmux'
  /** Backing OS session for async providers. Absent for `mode: 'api'`.
   *  Orchestrator persists `{kind,id}` to execution_logs, wires `close()`
   *  as the pending entry's `killSession`, and starts a liveness watchdog
   *  against `liveness()` so a tab the user closes manually can't leave the
   *  execution stuck as "in-flight" forever. */
  session?: SessionHandle
  /** Free-form hint for humans in log lines / UI (e.g. `tmux attach -t xyz`
   *  or `iTerm2 tab`). Not consumed by the orchestrator. */
  attachCmd?: string
  /** Sync providers set this when the run was cut short (e.g. server-side
   *  task budget exhausted, or the internal safety cap tripped). The
   *  orchestrator treats truncated runs as recoverable — it posts a
   *  progress notice instead of running the onFinish transition. */
  truncated?: boolean
  /** Underlying model stop_reason (`end_turn`, `pause_turn`, `max_tokens`,
   *  `hard_iter_cap`, …). Used for observability. */
  stopReason?: string
  /** Full raw Anthropic API response (JSON-stringified, capped) for the
   *  call that produced a truncated run. Only set alongside `truncated:
   *  true` — see `LoopResult.rawResponse` in packages/tools/src/contract.ts
   *  for why. Agent.ts persists this into the execution log's `errorMsg`
   *  so a truncated/paused/refused run has more than just a short
   *  `stopReason` string to debug from. */
  rawResponse?: string
  /** Per-run telemetry, when the provider can measure it. Sync providers
   *  fill this from `executeLoop`; async/terminal providers leave it
   *  undefined — the model runs in a Claude Code session this process
   *  never sees the token accounting for. The orchestrator persists it to
   *  the execution log, so `undefined` and `0` mean different things:
   *  "not measurable here" vs "measured, and it was zero". */
  metrics?: RunMetrics
}

/** Token totals for a whole run (every API call summed). Cache reads and
 *  cache writes stay separate from `inputTokens` because they bill at
 *  different rates. */
export interface RunUsage {
  inputTokens: number
  outputTokens: number
  cacheReadTokens: number
  cacheCreationTokens: number
}

export interface RunMetrics {
  usage: RunUsage
  /** API round-trips the agentic loop made. */
  iters: number
  toolCalls: number
  /** Tool calls that came back as an error — the signal for "this agent is
   *  missing a tool or a permission", which `stopReason` never shows. */
  toolErrors: number
}

/**
 * How a provider expects to receive its tool catalog.
 *   - `sync`: tools are handed to an LLM API natively (Anthropic `tools:`
 *     array). The engine exposes them via `toolExecution.getToolDefinitions`.
 *   - `async`: no native tool interface — the model runs in a terminal
 *     Claude session and calls back over HTTP. The engine appends a
 *     `toolExecution.buildToolInstructions` markdown block to the prompt
 *     describing each available tool + its curl invocation.
 */
export type ProviderKind = 'sync' | 'async'

export interface IAgentProvider {
  readonly id: string
  readonly kind: ProviderKind
  readonly name: string
  readonly description: string
  run(input: ProviderInput): Promise<ProviderOutput>
  /**
   * ¿Tomás esta tarea ahora? El provider decide; el engine sólo le pasa los
   * hechos que él ya tiene (`running`, `cap`) para que no tenga que
   * reimplementar el conteo ni leer config.
   *
   * Opcional: sin implementar, el engine aplica `withinDeclaredCap` — así el
   * cap de la UI vale para todos los providers sin que ninguno escriba una
   * línea. Implementalo cuando el provider sepa algo que el daemon no puede
   * saber: RAM del host, sesiones vivas, trabajo que no vino de este daemon,
   * un rate limit propio.
   *
   * Ver admission.ts para el contrato completo (consultivo, fail-open,
   * rechazar no es fallar).
   */
  canAccept?(req: AdmissionRequest): Promise<Admission>
  /**
   * ¿Dónde va a trabajar? El engine describe la tarea (`WorkspaceRequest`:
   * repos con coordenadas, branch, si el agente escribe) y el provider
   * devuelve el terreno concreto (`WorkspacePlan`: paths, cwd, writePaths).
   *
   * Misma filosofía que `canAccept`: el engine aporta hechos, decide el
   * provider. Antes esta decisión era un `if (providerId === 'anthropic-api')`
   * adentro del engine, con paths calculados sobre el disco del daemon — que
   * es exactamente lo que hacía imposible que un provider remoto trabajara
   * sobre un repo: recibía paths de otra máquina.
   *
   * Opcional: sin implementar, el run corre con los paths que el engine ya
   * conoce (el clone local del repo, sin worktree). El permiso de escritura
   * NO es del provider — el engine intersecta lo que devuelve contra
   * `needsWrite` (ver `intersectWritePaths` en @ia-flow/shared).
   */
  prepareWorkspace?(req: WorkspaceRequest): Promise<WorkspacePlan>
}

// ─── Injected ports ─────────────────────────────────────────────────────
//
// Providers in this package never import apps/server's tool registry, DB
// repos, or WorkspaceManager directly — they receive the narrow slice of
// that behavior they actually call, as plain functions, from whoever
// composes them (apps/server's composition/container.ts today).

/** Sandbox context a tool executes in. Mirrors apps/server's
 *  `tools/index.ts::ToolContext` field-for-field, except `policy`, which
 *  this package treats as opaque (it's forwarded, never read, here) — the
 *  concrete `ToolContext` (with a real `CompiledPolicy`) is structurally
 *  assignable wherever this type is expected. */
export interface ToolContext {
  repoPaths: Record<string, string>
  sourceContext?: unknown
  fileSimplifierEnabled?: boolean
  writePaths?: string[]
  taskId?: string
  policy?: unknown
}

export interface LoopOptions {
  onToolCall?: (name: string, input: unknown, toolUseId: string) => void
  onToolResult?: (name: string, result: string, toolUseId: string) => void
  signal?: AbortSignal
  logContext?: Record<string, unknown>
  /** See `LoopOptions.maxPauseTurnRetries` in packages/tools/src/contract.ts
   *  (the implementation's copy of this type) for the full rationale. */
  maxPauseTurnRetries?: number
  /** See `LoopOptions.retryTruncatedToolUse` in packages/tools/src/contract.ts
   *  (the implementation's copy of this type) for the full rationale. */
  retryTruncatedToolUse?: boolean
}

export interface LoopResult {
  text: string
  iters: number
  stopReason: string
  truncated: boolean
  usage: RunUsage
  toolCalls: number
  toolErrors: number
}

export interface ToolDefinitionsOptions {
  providerKind?: ProviderKind
  toolNames?: string[]
}

/** The agentic tool-execution engine, injected so `anthropic-api` never
 *  imports apps/server's tool registry directly. */
export interface ToolExecutionPort {
  getToolDefinitions(
    opts?: ToolDefinitionsOptions,
  ): Array<{ name: string; description: string; input_schema: object }>
  executeLoop(
    // `overrides` mirrors `FetchApiOverrides` in packages/tools/src/engine.ts
    // (kept `any`-shaped here, like the rest of this port, to avoid a
    // cross-package type import for a single internal knob).
    fetchApi: (messages: any[], overrides?: { bumpMaxTokens?: boolean }) => Promise<any>,
    initialMessages: any[],
    ctx: ToolContext,
    opts?: LoopOptions,
  ): Promise<LoopResult>
}

/** Resolves the per-project/global provider settings blob. Backed by
 *  apps/server's DB-persisted config; injected so providers stay
 *  storage-agnostic. */
export type LoadProviderConfig = () => Promise<ProviderConfig>

/**
 * Quien sabe materializar un `WorkspaceRequest` sobre un disco real:
 * clonar el repo si hace falta, crear/reusar el worktree, resolver scopes.
 *
 * Los providers de este paquete NO implementan eso — lo reciben inyectado,
 * igual que `toolExecution` o `loadProviderConfig`. La implementación vive en
 * `@ia-flow/workspace` (`WorktreeWorkspaceProvisioner` /
 * `TerminalWorkspaceProvisioner`) y la cablea el composition root; acá sólo
 * se declara la forma para no crear la dependencia de vuelta.
 */
export interface WorkspaceProvisionerPort {
  prepare(req: WorkspaceRequest): Promise<WorkspacePlan>
}

// ─── Pure config helpers (no I/O — safe to own here) ───────────────────

export const DEFAULT_ANTHROPIC_SETTINGS: AnthropicApiSettings = {
  model: 'claude-sonnet-4-6',
  anthropicVersion: '2023-06-01',
  anthropicBeta: [
    'claude-code-20250219',
    'oauth-2025-04-20',
    'interleaved-thinking-2025-05-14',
    'context-management-2025-06-27',
    'prompt-caching-scope-2026-01-05',
    'extended-cache-ttl-2025-04-11',
  ],
  systemPrompt: [],
  thinking: { type: 'adaptive' },
  stream: true,
  responseLanguage: 'español',
}

export const DEFAULT_TERMINAL_SETTINGS = {}

export const DEFAULT_PROVIDER_CONFIG: ProviderConfig = {
  steps: {
    'refine-functional': 'anthropic-api',
    'refine-technical': 'anthropic-api',
    implement: 'tmux-claude',
  },
  anthropicApi: DEFAULT_ANTHROPIC_SETTINGS,
  tmuxClaude: DEFAULT_TERMINAL_SETTINGS,
  itermClaude: DEFAULT_TERMINAL_SETTINGS,
}

/** Resolves the provider id and merged settings for a given step. Pure —
 *  step-level overrides take precedence over provider-level defaults. */
export function resolveStepSettings(
  step: StepType,
  config: ProviderConfig,
): { providerId: string; settings: AnthropicApiSettings } {
  const stepCfg = config.steps[step]
  if (typeof stepCfg === 'string') {
    return { providerId: stepCfg, settings: config.anthropicApi }
  }
  if (!stepCfg || typeof stepCfg === 'string') {
    throw new Error(`No provider configured for step '${step}'`)
  }
  const { provider, ...overrides } = stepCfg
  return { providerId: provider, settings: { ...config.anthropicApi, ...overrides } }
}
