import Anthropic from '@anthropic-ai/sdk'
import type { Task, TechnicalPRDs, RepoContext } from '@ia-flow/shared'

function placeholderPRDs(repos: string[]): TechnicalPRDs {
  const result: TechnicalPRDs = {}
  for (const repo of repos) {
    result[repo] = {
      repo,
      files_to_modify: [
        {
          path: 'CONFIGURE_API_KEY',
          change_type: 'modify',
          description: 'ANTHROPIC_API_KEY not configured. Set the key in apps/server/.env.',
        },
      ],
      test_scenarios: [
        {
          scenario: 'API key configuration',
          given: 'the server starts',
          when: 'ANTHROPIC_API_KEY is set',
          then: 'technical PRDs are generated by AI',
        },
      ],
      dependencies: [],
      open_questions: ['Set ANTHROPIC_API_KEY to enable AI generation'],
    }
  }
  return result
}

function buildSystemPrompt(): string {
  return `You are a senior software architect at LaHaus, a proptech company in Latin America.
Your job is to generate detailed Technical PRDs for each affected repository.

LaHaus stack context:
- Go services: hexagonal architecture, Echo/Gin, wire DI, golang-toolkit
- Python services: FastAPI, SQLAlchemy, Pydantic, UV, ruff
- Frontend: Vue 3, Nuxt 3, Pinia, Tailwind, TypeScript
- Infrastructure: AWS (SQS, S3, RDS), PostgreSQL, Redis, Kafka
- Patterns: Clean Architecture, dependency injection, event-driven

Return ONLY valid JSON (no markdown, no explanation) matching this schema:
{
  "<repo_name>": {
    "repo": "string",
    "files_to_modify": [
      {
        "path": "relative/path/to/file.ext",
        "change_type": "create|modify|delete",
        "description": "string"
      }
    ],
    "api_contract": {
      "endpoint": "/api/...",
      "method": "GET|POST|PUT|DELETE|PATCH",
      "request_schema": {},
      "response_schema": {}
    },
    "data_model_changes": "string or null",
    "test_scenarios": [
      {
        "scenario": "string",
        "given": "string",
        "when": "string",
        "then": "string"
      }
    ],
    "dependencies": [
      { "repo": "other-repo-name", "what": "string" }
    ],
    "open_questions": ["string"]
  }
}`
}

function buildUserPrompt(task: Task, contexts: RepoContext[]): string {
  const contextSections = contexts
    .map((ctx) => {
      const parts: string[] = [`### Repo: ${ctx.name} (${ctx.type})`]
      if (ctx.claude_md) parts.push(`CLAUDE.md:\n${ctx.claude_md.slice(0, 1500)}`)
      if (ctx.manifest) parts.push(`Manifest:\n${ctx.manifest.slice(0, 800)}`)
      if (ctx.directory_tree) parts.push(`Structure:\n${ctx.directory_tree.slice(0, 1000)}`)
      return parts.join('\n\n')
    })
    .join('\n\n---\n\n')

  return `Generate Technical PRDs for each of these repos: ${task.repos.join(', ')}

Task:
Title: ${task.title}
Description: ${task.description}

Repo contexts:
${contextSections || 'No repo contexts available.'}

Generate a Technical PRD for EACH repo listed. Be specific about file paths based on the repo structure shown.`
}

export async function generateTechnicalPRDs(
  task: Task,
  contexts: RepoContext[],
): Promise<TechnicalPRDs> {
  const apiKey = Bun.env.ANTHROPIC_API_KEY
  if (!apiKey) {
    console.warn('[technical-prd] ANTHROPIC_API_KEY not set, returning placeholder')
    return placeholderPRDs(task.repos)
  }

  const client = new Anthropic({ apiKey })

  try {
    const message = await client.messages.create({
      model: 'claude-sonnet-4-5',
      max_tokens: 8192,
      system: buildSystemPrompt(),
      messages: [
        {
          role: 'user',
          content: buildUserPrompt(task, contexts),
        },
      ],
    })

    const text = message.content
      .filter((b) => b.type === 'text')
      .map((b) => (b as { type: 'text'; text: string }).text)
      .join('')

    const jsonStr = text.replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '').trim()

    return JSON.parse(jsonStr) as TechnicalPRDs
  } catch (err) {
    console.error('[technical-prd] Error calling Claude:', err)
    throw err
  }
}
