import type { AgentProviderConfig, RepoWorkflow, SessionKind, StepType } from '@ia-flow/shared'

/**
 * Opaque handle to the OS-level backing of an async run (a tmux session, an
 * iTerm2 tab, …). Providers that spawn out-of-process work return one so the
 * orchestrator can persist its coordinates, close it on cancel, and watchdog
 * its liveness without knowing which technology backs it.
 *
 *  - `kind` + `id` are what we save to `execution_logs` so a stopped run can
 *    later be identified from the DB.
 *  - `isAlive()` should be cheap and side-effect-free (used by the poller).
 *  - `close()` must be idempotent — the watchdog and the manual cancel path
 *    may both fire, and complete_task / fail_task tools also invoke it.
 */
export interface SessionHandle {
  kind: SessionKind
  id: string
  isAlive: () => Promise<boolean>
  close: () => Promise<void>
}

/**
 * Input passed to a provider's run() method. Populated by AgentOrchestrator
 * before each agent invocation.
 *
 * The agent learns about repos via the `{{project.repos}}` / `{{task.repos}}`
 * template variables in its prompt. `repoPaths` is the raw name→path map
 * consumed by fs tools (`read_file`, `list_dir`, `grep_files`) to resolve
 * `<repo-name>/relative/path`.
 */
export interface ProviderInput {
  step: StepType
  /** Agent registry id (e.g. "code-reviewer"). Propagated to logs so every
   *  event can be filtered/joined by the agent that produced it. */
  agentId?: string
  /** Project id owning the task. Propagated to logs so the Logs tab in a
   *  project view can filter by projectId. */
  projectId?: string
  /** Correlation id shared by the execution_logs row and every log line
   *  emitted during this run. Generated by AgentOrchestrator. When absent,
   *  providers fall back to generating their own local runId. */
  runId?: string
  taskId: string
  taskTitle: string
  taskDescription: string
  taskType: string
  /** Repos linked to this task by name. */
  repos: string[]
  /** name → absolute filesystem path, wired into ToolContext.repoPaths. */
  repoPaths: Record<string, string>
  prompt: string
  systemPromptBlocks?: Array<{ type: 'text'; text: string }>
  tools?: string[]
  /**
   * Per-agent opt-out list forwarded from `AgentDefinition.disabledTools`.
   * `getToolDefinitions({ disabledTools })` drops these names before the
   * provider forwards them to the model, and `input.tools` filtering runs
   * on the already-pruned set. Terminal providers (tmux/iterm) apply the
   * same filter to their HTTP curl appendix.
   */
  disabledTools?: string[]
  providerConfig?: AgentProviderConfig
  /** Source-specific tool context, opaque to the domain. */
  sourceToolContext?: unknown
  cwd?: string
  workflow?: RepoWorkflow
  /**
   * Nombre canónico de la branch git para esta task (viene de `task.branch` —
   * linked branch de GitHub o valor auto-generado por el engine). Undefined
   * ⇒ providers usan el fallback `task/<taskId>`.
   */
  branch?: string
  /**
   * Absolute filesystem paths that write/edit/exec tools are allowed to touch
   * during this run. Wired into `ToolContext.writePaths` by the anthropic-api
   * provider. Populated by the WorkspaceManager for `implement`-step runs;
   * `undefined` or empty means the run has no writable zones (write tools
   * must refuse).
   */
  writePaths?: string[]
  /**
   * Compiled permission policy for this dispatch. When absent, the sandbox
   * falls back to `LEGACY_DEFAULT_POLICY` (pre-issue-58 behavior) so old
   * agents that still ship only `tools[]`/`disabledTools[]` keep working.
   * Threaded from `AgentOrchestrator.compilePolicy(agent.permissions |
   * preset)` into `ToolContext.policy`, where `bash_run` reads its bin
   * whitelist and git write scope.
   */
  policy?: import('../../application/policy.js').CompiledPolicy
  /** Aborts the run when triggered (e.g. the manual gate detects the source
   *  status has drifted from where the agent was dispatched). Providers
   *  should propagate to any long-running work (fetch calls, spawned
   *  sessions) and clean up so no partial transitions leak. */
  signal?: AbortSignal
}

/**
 * Result of a provider run.
 *   - Sync providers (anthropic-api) return `{ content, mode: 'api' }`.
 *   - Async providers (tmux-claude, iterm-claude) spawn a background
 *     session and return `{ content, mode: 'tmux', tmuxSession? }`. The
 *     final task transition is triggered later by the async agent via
 *     the complete_task / fail_task tools.
 */
export interface ProviderOutput {
  content: string
  mode: 'api' | 'tmux'
  /** Backing OS session for async providers. Absent for `mode: 'api'`.
   *  Orchestrator persists `{kind,id}` to execution_logs, wires `close()`
   *  as the pending entry's `killSession`, and starts a liveness watchdog
   *  against `isAlive()` so a tab the user closes manually can't leave the
   *  execution stuck as "in-flight" forever. */
  session?: SessionHandle
  /** Free-form hint for humans in log lines / UI (e.g. `tmux attach -t xyz`
   *  or `iTerm2 tab`). Not consumed by the orchestrator. */
  attachCmd?: string
  /** Sync providers set this when the run was cut short (e.g. server-side
   *  task budget exhausted, or the internal safety cap tripped). The
   *  orchestrator treats truncated runs as recoverable — it posts a
   *  progress notice instead of running the onFinish transition. */
  truncated?: boolean
  /** Underlying model stop_reason (`end_turn`, `pause_turn`, `max_tokens`,
   *  `hard_iter_cap`, …). Used for observability. */
  stopReason?: string
}

/**
 * How a provider expects to receive its tool catalog.
 *   - `sync`: tools are handed to an LLM API natively (Anthropic `tools:`
 *     array). The engine exposes them via `getToolDefinitions`.
 *   - `async`: no native tool interface — the model runs in a terminal
 *     Claude session and calls back over HTTP. The engine appends a
 *     `buildToolInstructions` markdown block to the prompt describing each
 *     available tool + its curl invocation.
 * Every `Tool` declares a `providerKinds` array to opt in/out per kind, so
 * write/exec tools that need the sandboxed `ToolContext.writePaths` scope
 * can stay `['sync']`-only.
 */
export type ProviderKind = 'sync' | 'async'

export interface IAgentProvider {
  readonly id: string
  readonly kind: ProviderKind
  readonly name: string
  readonly description: string
  run(input: ProviderInput): Promise<ProviderOutput>
}
